apply plugin: 'com.android.library'

android {
    namespace 'com.pzy.starfall.mobile'
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 36
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.window:window-java:1.5.1'
}
